### ISSUE TITLE
Parsing failure of LVM Snapshot with LANG/LC_ALL not set to "C"

### ISSUE THREAD

**Issue by ndi123** [holland-backup/holland#224] opened 2018-10-26 08:36 UTC
There is a quite old bug report in old holland-backup launchpad which is still not fixed: https://bugs.launchpad.net/holland-backup/+bug/1256121

holland backup is not able to parse the volume group / logical volume when locale is not set to "C"

How to reproduce: LANG="de_DE.UTF-8" LC_ALL="" holland backup
Workaround: LANG=C LC_ALL=C holland backup

There is also a possible patch in launchpad: https://launchpadlibrarian.net/166654937/lang.patch

I hope this bug will be fixed finally 👍

**Comment by a5a351e7** [comment] 2018-10-26 08:44
Yeah, got this issue too. The integration of the patch would be very nice!

**Comment by soulen3** [comment] 2018-10-29 18:17
Thank you for reporting this again. I haven't been looking at launchpad for bugs.
I'm not able to reproduce this bug.  What environment are you using?

I tried this on Debian 9 and Ubuntu 18, but that lead me to #226

**Comment by soulen3** [comment] 2018-10-29 20:51
I'm also using Centos 7, so I'm not why it works on my on my machine and not yours.  This will be included when 1.1.9 is tagged as a release. (I haven't decided on a date for that yet)

**Comment by ndi123** [comment] 2018-10-30 09:03
I don't think that this bug is OS dependent. I already saw it on Ubuntu 12.04, Ubuntu 14,04, Ubuntu 16.04, Debian 8, Debian 9, RHEL 6.X and CentOS 7.

I can reproduce it setting LANG to de_DE.UTF-8

# LANG="de_DE.UTF-8" LC_ALL="" holland backup
Holland 1.1.8 started with pid 842
--- Starting backup run ---
Creating backup path /srv/backup/holland/lvmdump/20181030_095823
Estimating size of mysqldump backup
Estimated Backup Size: 299.63MB
Using Historic Space Estimate: Checking for information in /srv/backup/holland/lvmdump/newest/backup.conf
Last backup used 189.97MB
Adjusting estimated size to last backup total * 1.1: 208.97MB
Starting backup[lvmdump/20181030_095823] via plugin mysqldump-lvm
Backing up /db/mysql via snapshot
Auto-sizing snapshot-size to 1.00GB (256 extents)
Acquiring read-lock and flushing tables
This MySQL server does not have binary logs enabled. Nothing to record from SHOW MASTER STATUS.
This MySQL server is not a slave. Nothing to record from SHOW SLAVE STATUS
Created snapshot volume /dev/snapshot/db_snapshot
Releasing read-lock

Released lock /etc/holland/backupsets/lvmdump.conf
Uncaught exception while running command 'holland backup': LookupError()
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/holland/core/command/command.py", line 110, in dispatch
    return self.run(self.optparser.prog, opts, *args)
  File "/usr/lib/python2.7/site-packages/holland/commands/backup.py", line 117, in run
    runner.backup(name, config, opts.dry_run)
  File "/usr/lib/python2.7/site-packages/holland/core/backup/base.py", line 153, in backup
    plugin.backup()
  File "/usr/lib/python2.7/site-packages/holland/backup/mysql_lvm/plugin/mysqldump/plugin.py", line 126, in backup
    snapshot.start(volume)
  File "/usr/lib/python2.7/site-packages/holland/lib/lvm/snapshot.py", line 35, in start
    return self.create_snapshot(volume)
  File "/usr/lib/python2.7/site-packages/holland/lib/lvm/snapshot.py", line 54, in create_snapshot
    return self.mount_snapshot(snapshot)
  File "/usr/lib/python2.7/site-packages/holland/lib/lvm/snapshot.py", line 62, in mount_snapshot
    if snapshot.filesystem() == 'xfs':
  File "/usr/lib/python2.7/site-packages/holland/lib/lvm/base.py", line 296, in filesystem
    raise LookupError()
LookupError

**Closed** 2018-10-30 16:56 UTC
