### ISSUE TITLE
Python error - not all arguments converted during string formatting

### ISSUE THREAD

**Issue by wojtas911** [holland-backup/holland#153] opened 2016-09-30 07:22 UTC
# holland bk --dry-run

Holland 1.0.10 started with pid 19703
--- Starting dry run ---
Creating backup path /var/spool/holland/default/20160930_092008
Estimating size of mysqldump backup
Backup failed after 0.01 seconds
Uncaught exception while running command 'bk': TypeError('not all arguments converted during string formatting',)
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/holland/core/command/command.py", line 209, in dispatch
    return self.run(self.optparser.prog, opts, *args)
  File "build/bdist.linux-x86_64/egg/holland/commands/backup.py", line 102, in run
    runner.backup(name, config, opts.dry_run)
  File "build/bdist.linux-x86_64/egg/holland/core/backup/base.py", line 120, in backup
    estimated_size = self.check_available_space(plugin, spool_entry, dry_run)
  File "build/bdist.linux-x86_64/egg/holland/core/backup/base.py", line 213, in check_available_space
    estimated_bytes_required = plugin.estimate_backup_size()
  File "build/bdist.linux-x86_64/egg/holland/backup/mysqldump/plugin.py", line 123, in estimate_backup_size
    self.schema.refresh(db_iter=db_iter, tbl_iter=tbl_iter)
  File "build/bdist.linux-x86_64/egg/holland/lib/mysql/schema/base.py", line 135, in refresh
    for table in tbl_iter(database.name):
  File "build/bdist.linux-x86_64/egg/holland/lib/mysql/schema/base.py", line 293, in **call**
    for metadata in self.client.show_table_metadata(database):
  File "build/bdist.linux-x86_64/egg/holland/lib/mysql/client/base.py", line 198, in show_table_metadata
    return self._show_table_metadata51(database)
  File "build/bdist.linux-x86_64/egg/holland/lib/mysql/client/base.py", line 181, in _show_table_metadata51
    cursor.execute(sql, (database))
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 198, in execute
    query = query % args
TypeError: not all arguments converted during string formatting
# holland --version

Holland Backup v1.0.10
Copyright (c) 2008-2010 Rackspace US, Inc.
More info available at http://hollandbackup.org
# lsb_release -a

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 15.10
Release:    15.10
Codename:   wily
# holland lp

Holland 1.0.10 started with pid 19720
## Plugin-Type  Plugin-Name     Version   Author           Summary

backup       mysqldump       1.0.10dev-r0 Rackspace        MySQLDump Backup/Restore Plugins
backup       xtrabackup      1.0.10dev-r0 Rackspace        Xtrabackup Plugin for Holland
command      backup          1.0.10    Rackspace        Holland Core Plugins
command      help            1.0.10    Rackspace        Holland Core Plugins
command      listbackups     1.0.10    Rackspace        Holland Core Plugins
command      listplugins     1.0.10    Rackspace        Holland Core Plugins
command      mk-config       1.0.10    Rackspace        Holland Core Plugins
command      purge           1.0.10    Rackspace        Holland Core Plugins

**Comment by carlwgeorge** [comment] 2017-04-25 14:59
This is a duplicate of #106 and was fixed in 1.0.12.

**Closed** 2017-07-06 03:01 UTC
